=== LidiaMorina/Laba_5-DOM-/tariff_xsdShema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Tariff">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tariffs" minOccurs="2" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="operator" type="xs:string" />
                            <xs:element name="payroll" type="xs:short" />
                            <xs:element name="call_prices">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="withinNetwork" type="xs:float"/>
                                        <xs:element name="outsideNetwork" type="xs:float"/>
                                        <xs:element name="fixedPhone" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sms_price" type="xs:float" />
                            <xs:element name="parameters" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="favoriteNumber" type="xs:float"/>
                                        <xs:element name="tariffication" type="xs:string"/>
                                        <xs:element name="paymentConnection" type="xs:byte"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="tariffName"
                                      type="xs:string"
                                      use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== LidiaMorina/Laba_5-DOM-/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tariff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="tariff_xsdShema.xsd">
	<tatiff_name name="black">
		<operator>Tele2 </operator>
		<payroll> 350</payroll>
	    <call_prices>
			<withinNetwork> 0.5 </withinNetwork>
			<outsideNetwork> 5 </outsideNetwork>
			<fixedPhone> 10 </fixedPhone>
		</call_prices>
		
		<sms_price> 2 </sms_price>
		
		<parameters>
			<favoriteNumber> 3 </favoriteNumber>
			<tariffication> 1min </tariffication>
			<paymentConnection> 0 </paymentConnection>
		</parameters>
	</tatiff_name>


	<tatiff_name name="myOnline">
		<operator> MTS </operator>
		<payroll> 550 </payroll>
	    <call_prices>
			<withinNetwork> 0.2 </withinNetwork>
			<outsideNetwork> 2 </outsideNetwork>
			<fixedPhone> 5 </fixedPhone>
		</call_prices>
		
		<sms_price> 1.5 </sms_price>
		
		<parameters>
			<favoriteNumber> 5 </favoriteNumber>
			<tariffication> 12sec </tariffication>
			<paymentConnection> 0 </paymentConnection>
		</parameters>
	</tatiff_name>
	
	<tatiff_name name="yellow">
		<operator> bilain </operator>
		<payroll> 150 </payroll>
	    <call_prices>
			<withinNetwork> 1.5 </withinNetwork>
			<outsideNetwork> 7 </outsideNetwork>
			<fixedPhone> 12 </fixedPhone>
		</call_prices>
		
		<sms_price> 1 </sms_price>
		
		<parameters>
			<favoriteNumber>8</favoriteNumber>
			<tariffication>1 min</tariffication>
			<paymentConnection>233</paymentConnection>
		</parameters>
	</tatiff_name>
	
	<tatiff_name name="yellow_2">
		<operator> bilain_2 </operator>
		<payroll> 110 </payroll>
	    <call_prices>
			<withinNetwork> 1.3 </withinNetwork>
			<outsideNetwork> 2 </outsideNetwork>
			<fixedPhone> 12 </fixedPhone>
		</call_prices>
		
		<sms_price> 4 </sms_price>
		
		<parameters>
			<favoriteNumber>2</favoriteNumber>
			<tariffication>1 min</tariffication>
			<paymentConnection>253</paymentConnection>
		</parameters>
	</tatiff_name>
	
	<tatiff_name name="dark">
		<operator> qwerty </operator>
		<payroll> 417 </payroll>
	    <call_prices>
			<withinNetwork> 1.7 </withinNetwork>
			<outsideNetwork> 3 </outsideNetwork>
			<fixedPhone> 12 </fixedPhone>
		</call_prices>
		
		<sms_price> 3 </sms_price>
		
		<parameters>
			<favoriteNumber>2</favoriteNumber>
			<tariffication>1 min</tariffication>
			<paymentConnection>213</paymentConnection>
		</parameters>
	</tatiff_name>
</Tariff>
